# $(curl -skL "https://raw.githubusercontent.com/satinjeet/shell_utilities/master/load_library.sh?$(date +%s)" > /tmp/load_library.sh)

source $PWD/load_library.sh

load_lib -a $PWD/colors colors

echo "${COLOR_DEFAULT}COLOR_DEFAULT${COLOR_DEFAULT}";
echo "${COLOR_BLACK}COLOR_BLACK${COLOR_DEFAULT}";
echo "${COLOR_RED}COLOR_RED${COLOR_DEFAULT}";
echo "${COLOR_GREEN}COLOR_GREEN${COLOR_DEFAULT}";
echo "${COLOR_YELLOW}COLOR_YELLOW${COLOR_DEFAULT}";
echo "${COLOR_BLUE}COLOR_BLUE${COLOR_DEFAULT}";
echo "${COLOR_MAGENTA}COLOR_MAGENTA${COLOR_DEFAULT}";
echo "${COLOR_CYAN}COLOR_CYAN${COLOR_DEFAULT}";
echo "${COLOR_LIGHT_GRAY}COLOR_LIGHT_GRAY${COLOR_DEFAULT}";
echo "${COLOR_DARK_GRAY}COLOR_DARK_GRAY${COLOR_DEFAULT}";
echo "${COLOR_LIGHT_RED}COLOR_LIGHT_RED${COLOR_DEFAULT}";
echo "${COLOR_LIGHT_GREEN}COLOR_LIGHT_GREEN${COLOR_DEFAULT}";
echo "${COLOR_LIGHT_YELLOW}COLOR_LIGHT_YELLOW${COLOR_DEFAULT}";
echo "${COLOR_LIGHT_BLUE}COLOR_LIGHT_BLUE${COLOR_DEFAULT}";
echo "${COLOR_LIGHT_MAGENTA}COLOR_LIGHT_MAGENTA${COLOR_DEFAULT}";
echo "${COLOR_LIGHT_CYAN}COLOR_LIGHT_CYAN${COLOR_DEFAULT}";
echo "${COLOR_WHITE}COLOR_WHITE${COLOR_DEFAULT}";