#!/bin/bash
# arrow-detect.sh: Detects the arrow keys, and a few more.
# Thank you, Sandro Magi, for showing me how.
 
# --------------------------------------------
# Character codes generated by the keypresses.
arrowup='\[A'
arrowdown='\[B'
arrowrt='\[C'
arrowleft='\[D'
insert='\[2'
delete='\[3'
enter=''
# --------------------------------------------
 
SUCCESS=0
OTHER=65

KEY_LEFT="LEFT"
KEY_RIGHT="RIGHT"
KEY_UP="UP"
KEY_DOWN="DOWN"
KEY_ENTER="ENTER"

read_arrow_key() {
    # May need to also press ENTER if a key not listed above pressed.
    read -sn3 key                      # Read 3 characters.
    OUTPT="~"
    echo "$key" | grep "$arrowup"  #Check if character code detected.
    if [ "$?" -eq $SUCCESS ]
    then
        echo $KEY_UP
        return 0
    fi
    
    echo "$key" | grep "$arrowdown"
    if [ "$?" -eq $SUCCESS ]
    then
        echo $KEY_DOWN
        return 0
    fi
    
    echo "$key" | grep "$arrowrt"
    if [ "$?" -eq $SUCCESS ]
    then
        echo $KEY_RIGHT
        return 0
    fi
    
    echo "$key" | grep "$arrowleft"
    if [ "$?" -eq $SUCCESS ]
    then
        echo $KEY_LEFT
        return 0
    fi

    if [ "$key" == "" ]
    then
        echo $KEY_ENTER
        return 0
    fi

    echo $OUTPT; 
}

p=`read_arrow_key`
echo $p;